### ISSUE TITLE
setup/before in describe

### ISSUE THREAD

**Issue by nhu313** [drewolson/ex_spec#2]
Are you accepting feature request? I would like to be able to do a setup for a describe/context block. 

``` elixir
  describe "addition" do
    setup do
      IO.puts "I'm only setting up for this describe"
      :ok
    end

    test "2 plus 1" do
      assert (2 + 1) == 3
    end

    test "3 plus 1" do
      assert (3 + 1) == 4
    end
  end

  test "1 plus 1" do
    assert (1 + 1) == 2
  end
```

Ideally "I'm only setting up for this describe" is only printed twice. What do you think?

**Comment by drewolson** [comment]
Thanks for opening this issues. At this point I firmly believe that `ex_spec` should be a very simple wrapper around ExUnit that is only focused on test organization.

There are several other projects aimed at creating a most "full featured" BDD experience (e.g. shouldi). I'd encourage you to check out those projects if you're interested in this type of functionality.

Hope this makes sense.

**Comment by stevegraham** [comment]
I'd like to +1 this.
