### ISSUE TITLE
How to use with Phoenix?

### ISSUE THREAD

**Issue by cjbottaro** [drewolson/ex_spec#3]
Hi.  How do I use this with Phoenix?  Phoenix uses `ExUnit.CaseTemplate`.  It is `use`ed in:

```
YourApp.ModelCase
YourApp.ChannelCase
YourApp.ConnCase
```

Then those are `use`ed in your actual test files.

Thanks for the help.

**Comment by drewolson** [comment]
Hi @cjbottaro. [Here](https://github.com/drewolson/blox/blob/master/test/test_helper.exs) is an example where I'm using ex_spec with Phoenix (though the example is on an older version of phoenix). The short answer is just modify `YourApp.ModelCase`'s `using` block to `use ExSpec` (as well as the other files) and everything should work just fine!

**Comment by drewolson** [comment]
Here's an example from a brand new, generated phoenix project:

https://gist.github.com/drewolson/a2d48314b6984835eaf4f3e1df1f0e1a

Note: the only addition from the generated file is [this line](https://gist.github.com/drewolson/a2d48314b6984835eaf4f3e1df1f0e1a#file-conn_case-ex-L21).
